# Generated by Django 3.2.13 on 2022-10-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_name',
            field=models.CharField(choices=[('인생은 아름다워', '인생은 아름다워'), ('정직한 후보 2', '정직한 후보 2'), ('공조2: 인터내셔날', '공조2: 인터내셔날'), ('듄', '듄'), ('극장판 짱구는 못말려: 수수께끼! 꽃피는 천하떡잎학교', '극장판 짱구는 못말려: 수수께끼! 꽃피는 천하떡잎학교'), ('스마일', '스마일'), ('인터스텔라', '인터스텔라'), ('티켓 투 파라다이스', '티켓 투 파라다이스')], max_length=30),
        ),
    ]
