# Generated by Django 3.2.13 on 2022-10-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('movies', '0003_alter_review_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
