# Generated by Django 3.2.13 on 2022-10-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('join_at', models.DateTimeField(auto_now_add=True, verbose_name='가입시간')),
            ],
            options={
                'db_table': 'test_user',
            },
        ),
    ]
